export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_CURRENT_PRODUCT = 'SET_CURRENT_PRODUCT'

export const SET_BUILDS = 'SET_BUILDS'
export const SET_CURRENT_BUILD = 'SET_CURRENT_BUILD'
export const ONCHANGE_NEW_BUILD_FORM = 'ONCHANGE_NEW_BUILD_FORM'

export const IS_ACTIVE = 'IS_ACTIVE'
